#AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

git_url = "https://github.com/gkennos/wimlds_fastai/tree/master/"

def custom_doc_links(name): return None